// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WegaisApp.Core.DB;

#nullable disable

namespace WegaisApp.Core.Migrations
{
    [DbContext(typeof(WegaisContext))]
    partial class WegaisContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("WegaisApp.Core.DB.Entities.Producer", b =>
                {
                    b.Property<string>("ClientRegId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdressDescription")
                        .HasColumnType("TEXT");

                    b.Property<int>("Country")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Inn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kpp")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RegionCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ClientRegId");

                    b.ToTable("Producers");
                });

            modelBuilder.Entity("WegaisApp.Core.DB.Entities.Product", b =>
                {
                    b.Property<string>("AlcCode")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AlcVolume")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Capacity")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProducerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductVCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AlcCode");

                    b.HasIndex("ProducerId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("WegaisApp.Core.DB.Entities.StockPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("InformF1RegId")
                        .HasColumnType("TEXT");

                    b.Property<string>("InformF2RegId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("StockPositions");
                });

            modelBuilder.Entity("WegaisApp.Core.DB.Entities.Product", b =>
                {
                    b.HasOne("WegaisApp.Core.DB.Entities.Producer", "Producer")
                        .WithMany("Products")
                        .HasForeignKey("ProducerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producer");
                });

            modelBuilder.Entity("WegaisApp.Core.DB.Entities.StockPosition", b =>
                {
                    b.HasOne("WegaisApp.Core.DB.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WegaisApp.Core.DB.Entities.Producer", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
